/**
 * preprocessor.ts — the GLSL ES 1.00 / 3.00 preprocessor stage (spec §3.4).
 *
 * Pipeline position: `compileShader` runs preprocessor → lexer → parser →
 * semantics. This module consumes the raw shader source and emits a flat token
 * stream (RawToken[]) with every directive processed and every macro expanded,
 * plus the declared `#version`, the final extension state and every
 * `#extension` directive (the parser later converts those into ExtensionDecl
 * AST nodes). It performs no syntax validation of shader code — characters the
 * lexer rejects (e.g. `@`) pass through as single-char tokens.
 *
 * C-preprocessor semantics (GLSL ES inherits the C model): backslash-newline
 * line splicing; `//` and block-comment stripping (no nesting; newlines inside
 * block comments retained); object-like and function-like macros with `#`
 * stringize and `##` token paste; argument pre-expansion except adjacent to
 * `#`/`##`; full re-scan with recursion suppression via per-token hide sets
 * (A→B, B→A terminates); predefined macros __LINE__/__FILE__/__VERSION__/
 * GL_ES; `#extension` macros (enable/require define the name = 1, disable
 * removes it, warn defines nothing; `all` works with warn/disable only);
 * `#if`/`#elif`/`#ifdef`/`#ifndef`/`#else`/`#endif` with full integer constant
 * expression evaluation (`defined(NAME)` / `defined NAME`, C precedence,
 * 32-bit shifts, division by zero → 0, undefined identifiers → error per
 * GLSL ES §3.4); skipped branches are consumed but never expanded (directive
 * lines inside an inactive group are ignored entirely); `#error`; `#pragma`
 * (ignored); `#version` (exactly one); `#line` (1-arg in ESSL 1.00, optional
 * integer source-string-number in 3.00; the line following the directive
 * becomes the number).
 * WebGL requirements: `defined` may not be used as a macro name, and a
 * `defined` token generated by macro expansion inside `#if` is an error.
 *
 * Errors: 1-based lines (after `#line` remapping), Khronos-style free-form
 * messages; all errors are collected and processing continues where possible.
 */
import type { CompileError } from './compiler.js';

// ------------------------------------------------------------------
// Public interface (consumed by the lexer stage)
// ------------------------------------------------------------------

export interface RawToken {
  /** Raw token text (identifier, number, punctuator, string literal...). */
  text: string;
  /** 1-based line AFTER #line remapping. */
  line: number;
  /** 0-based column within the line. */
  column: number;
}

export type ExtensionBehavior = 'require' | 'enable' | 'warn' | 'disable';

export interface ExtensionDirective {
  name: string;
  behavior: ExtensionBehavior;
  line: number;
}

export type PreprocessResult =
  | { ok: true; tokens: RawToken[]; version: 100 | 300; extensions: string[]; extensionDirectives: ExtensionDirective[] }
  | { ok: false; errors: CompileError[] };

export interface PreprocessOptions {
  /** Highest GLSL version the CONTEXT supports (100 = WebGL1, 300 = WebGL2). */
  version: 100 | 300;
  /** Extra preprocessor defines injected before the source (object-like). */
  defines?: Record<string, string>;
  /** Extensions the context supports; `#extension X : require|enable` of an unsupported name is an error. */
  extensions?: Set<string>;
}

// ------------------------------------------------------------------
// Internal model
// ------------------------------------------------------------------

/** A char of the spliced, comment-stripped stream with its physical line. */
interface Char {
  ch: string;
  line: number;
}

/**
 * Internal preprocessor token: source position plus `ws` (preceded by
 * whitespace — prevents function-like invocation) and `hidden` (macro names
 * suppressed from re-expansion, the C "hide set" that makes A→B, B→A
 * terminate).
 */
interface PToken {
  text: string;
  line: number;
  column: number;
  ws: boolean;
  hidden: Set<string> | null;
  /** Token-paste operator marker (only inside macro replacement lists). */
  paste?: boolean;
}

interface Macro {
  name: string;
  /** null = object-like macro; otherwise the parameter names. */
  params: string[] | null;
  /** Replacement-list tokens (from the #define line; raw, unexpanded). */
  body: PToken[];
  paramIndex: Map<string, number>;
  /** Per-parameter: true when adjacent to `#`/`##` (argument NOT pre-expanded). */
  rawArgs: boolean[];
  /** Predefined dynamic macros expand to a computed number. */
  kind: 'normal' | 'line' | 'file' | 'version' | 'gl_es';
}

interface CondFrame {
  parentActive: boolean;
  taken: boolean;
  active: boolean;
  elseSeen: boolean;
  /** Remapped line of the #if (reported for unterminated conditionals). */
  line: number;
}

/** Mutable state threaded through directive handling and expansion. */
interface State {
  macros: Map<string, Macro>;
  version: 100 | 300;
  lineOffset: number;
  errors: CompileError[];
  extState: Map<string, ExtensionBehavior>;
  allState: ExtensionBehavior | null;
  extensionDirectives: ExtensionDirective[];
  condStack: CondFrame[];
  /** Any token or non-#version directive seen before #version (spec: #version must be first). */
  sawContent: boolean;
  /** A #version directive has already been processed (spec: at most one). */
  versionSeen: boolean;
  opts: PreprocessOptions;
}

// ------------------------------------------------------------------
// Small helpers
// ------------------------------------------------------------------

const IDENT_RE = /^[A-Za-z_][A-Za-z0-9_]*$/;
const isIdent = (s: string): boolean => IDENT_RE.test(s);
const isDigit = (c: string): boolean => c >= '0' && c <= '9';
const isHexDigit = (c: string): boolean => (c >= '0' && c <= '9') || (c >= 'a' && c <= 'f') || (c >= 'A' && c <= 'F');
const isIdentStart = (c: string): boolean => (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || c === '_';
const isIdentChar = (c: string): boolean => isIdentStart(c) || isDigit(c);
const isSpace = (c: string): boolean => c === ' ' || c === '\t' || c === '\r' || c === '\v' || c === '\f';
/** Number suffix letters (uint/float suffixes are consumed greedily). */
const isSuffix = (c: string): boolean => c === 'u' || c === 'U' || c === 'f' || c === 'F';

const remap = (st: State, line: number): number => line + st.lineOffset;

function condActive(st: State): boolean {
  return st.condStack.length === 0 || st.condStack[st.condStack.length - 1].active;
}

function addHidden(h: Set<string> | null, name: string): Set<string> {
  const s = h ? new Set(h) : new Set<string>();
  s.add(name);
  return s;
}

function unionHidden(a: Set<string> | null, b: Set<string> | null): Set<string> | null {
  if (!a && !b) return null;
  const s = new Set<string>();
  if (a) for (const x of a) s.add(x);
  if (b) for (const x of b) s.add(x);
  return s;
}

const hasHidden = (t: PToken, name: string): boolean => t.hidden !== null && t.hidden.has(name);

/** Mark `##` tokens in a replacement list as paste operators. */
function markPastes(tokens: PToken[]): PToken[] {
  return tokens.map((t) => (t.text === '##' ? { ...t, paste: true } : t));
}

/** Perform the token-paste pass over a substituted replacement list. */
function pasteTokens(out: PToken[]): PToken[] {
  const res: PToken[] = [];
  for (let i = 0; i < out.length; i++) {
    const t = out[i];
    if (!t.paste) {
      res.push(t);
      continue;
    }
    // `##`: paste the next non-marker token onto the previous result.
    let j = i + 1;
    while (j < out.length && out[j].paste) j++;
    if (j >= out.length) break; // trailing ##: dropped (permissive)
    const right = out[j];
    if (res.length > 0) {
      const left = res[res.length - 1];
      res[res.length - 1] = {
        text: left.text + right.text,
        line: left.line,
        column: left.column,
        ws: left.ws,
        hidden: unionHidden(left.hidden, right.hidden),
      };
    } else {
      res.push({ ...right }); // leading ##: nothing to paste onto (permissive)
    }
    i = j;
  }
  return res;
}

/** Re-tag replacement tokens with the invocation site position (__LINE__ etc. use it). */
function retag(body: PToken[], inv: PToken): PToken[] {
  return body.map((b) => ({ ...b, line: inv.line, column: inv.column }));
}

/** `#x` stringize: argument tokens → one string-literal token. */
function stringize(arg: PToken[], inv: PToken): PToken {
  let s = '';
  for (let i = 0; i < arg.length; i++) {
    if (i > 0) s += ' ';
    s += arg[i].text;
  }
  s = s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
  return { text: '"' + s + '"', line: inv.line, column: inv.column, ws: false, hidden: null };
}

// ------------------------------------------------------------------
// Phase 1: line splicing
// ------------------------------------------------------------------

/**
 * Splice backslash-newline (and backslash-\r\n / backslash-\r) pairs BEFORE
 * comment and directive processing, per C phase 2 / GLSL ES sec. 3.4. `\r` and
 * `\r\n` are normalized to `\n`. Every char keeps its physical line number.
 */
function splice(source: string): Char[] {
  const out: Char[] = [];
  let line = 1;
  let i = 0;
  const n = source.length;
  while (i < n) {
    const c = source[i];
    if (c === '\\') {
      const next = source[i + 1];
      if (next === '\n') {
        // Splice: the continuation is part of the SAME logical line, so the
        // physical line counter does not advance (per GLSL ES §3.4 / C phase 2).
        i += 2;
        continue;
      }
      if (next === '\r') {
        if (source[i + 2] === '\n') {
          i += 3;
          continue;
        }
        i += 2;
        continue;
      }
    }
    if (c === '\r') {
      if (source[i + 1] === '\n') {
        out.push({ ch: '\n', line });
        i += 2;
        line++;
        continue;
      }
      out.push({ ch: '\n', line });
      i++;
      line++;
      continue;
    }
    if (c === '\n') {
      out.push({ ch: '\n', line });
      i++;
      line++;
      continue;
    }
    out.push({ ch: c, line });
    i++;
  }
  return out;
}

// ------------------------------------------------------------------
// Phase 2: comment stripping
// ------------------------------------------------------------------

/**
 * Replace `//` comments (to end of line) with nothing and block comments
 * with a single space (newlines inside block comments are retained so line
 * structure is preserved). An unterminated block comment is an error.
 */
function stripComments(chars: Char[], errors: CompileError[]): Char[] {
  const out: Char[] = [];
  let i = 0;
  const n = chars.length;
  while (i < n) {
    const c = chars[i];
    if (c.ch === '/' && i + 1 < n && chars[i + 1].ch === '/') {
      while (i < n && chars[i].ch !== '\n') i++;
      continue;
    }
    if (c.ch === '/' && i + 1 < n && chars[i + 1].ch === '*') {
      const startLine = c.line;
      i += 2;
      let closed = false;
      while (i < n) {
        if (chars[i].ch === '*' && i + 1 < n && chars[i + 1].ch === '/') {
          i += 2;
          closed = true;
          break;
        }
        if (chars[i].ch === '\n') {
          out.push(chars[i]);
          i++;
          continue;
        }
        i++;
      }
      if (!closed) {
        errors.push({ line: startLine, message: 'unterminated comment' });
        continue;
      }
      out.push({ ch: ' ', line: startLine });
      continue;
    }
    out.push(chars[i]);
    i++;
  }
  return out;
}

// ------------------------------------------------------------------
// Phase 3: tokenization
// ------------------------------------------------------------------

const PUNCT3: ReadonlySet<string> = new Set(['<<=', '>>=']);
const PUNCT2: ReadonlySet<string> = new Set([
  '<<', '>>', '&&', '||', '==', '!=', '<=', '>=', '^^',
  '+=', '-=', '*=', '/=', '%=', '&=', '|=', '^=', '++', '--', '##',
]);

/** Scan a number literal (dec/oct/hex, float, exponent, u/f suffix). */
function scanNumber(chars: Char[], i: number): { text: string; next: number } {
  let j = i;
  const n = chars.length;
  if (chars[j].ch === '0' && j + 1 < n && (chars[j + 1].ch === 'x' || chars[j + 1].ch === 'X')) {
    j += 2;
    while (j < n && isHexDigit(chars[j].ch)) j++;
    while (j < n && isSuffix(chars[j].ch)) j++;
    return { text: chars.slice(i, j).map((x) => x.ch).join(''), next: j };
  }
  while (j < n && isDigit(chars[j].ch)) j++;
  if (j < n && chars[j].ch === '.') {
    j++;
    while (j < n && isDigit(chars[j].ch)) j++;
  }
  if (j < n && (chars[j].ch === 'e' || chars[j].ch === 'E')) {
    let k = j + 1;
    if (k < n && (chars[k].ch === '+' || chars[k].ch === '-')) k++;
    if (k < n && isDigit(chars[k].ch)) {
      j = k;
      while (j < n && isDigit(chars[j].ch)) j++;
    }
  }
  while (j < n && isSuffix(chars[j].ch)) j++;
  return { text: chars.slice(i, j).map((x) => x.ch).join(''), next: j };
}

/**
 * Tokenize the cleaned stream. Whitespace is dropped; newlines are kept as
 * `\n` tokens (directive detection needs line boundaries); every other run of
 * characters becomes a token (identifiers, numbers, punctuators, single
 * chars — `"` is a single-char token; the lexer validates characters later).
 */
function tokenize(chars: Char[]): PToken[] {
  const out: PToken[] = [];
  let i = 0;
  let col = 0;
  let lastEnd = 0; // index in chars just past the previous token (ws detection)
  const n = chars.length;
  while (i < n) {
    const c = chars[i];
    if (c.ch === '\n') {
      out.push({ text: '\n', line: c.line, column: 0, ws: false, hidden: null });
      i++;
      col = 0;
      continue;
    }
    if (isSpace(c.ch)) {
      i++;
      col++;
      continue;
    }
    const start = i;
    const ws = start !== lastEnd;
    let text: string;
    if (isIdentStart(c.ch)) {
      let j = i + 1;
      while (j < n && isIdentChar(chars[j].ch)) j++;
      text = chars.slice(i, j).map((x) => x.ch).join('');
      i = j;
    } else if (isDigit(c.ch) || (c.ch === '.' && i + 1 < n && isDigit(chars[i + 1].ch))) {
      const r = scanNumber(chars, i);
      text = r.text;
      i = r.next;
    } else if (c.ch === '"') {
      // String literal: ONE token (so stringize/#error preserve it verbatim).
      // Backslash escapes do not close the literal; an unterminated literal
      // runs to the end of the line (the lexer validates it later).
      let j = i + 1;
      while (j < n && chars[j].ch !== '\n') {
        if (chars[j].ch === '\\' && j + 1 < n && chars[j + 1].ch !== '\n') {
          j += 2;
          continue;
        }
        if (chars[j].ch === '"') break;
        j++;
      }
      if (j < n && chars[j].ch === '"') j++;
      text = chars.slice(i, j).map((x) => x.ch).join('');
      i = j;
    } else {
      const two = c.ch + (i + 1 < n ? chars[i + 1].ch : '');
      const three = two + (i + 2 < n ? chars[i + 2].ch : '');
      if (PUNCT3.has(three)) {
        text = three;
        i += 3;
      } else if (PUNCT2.has(two)) {
        text = two;
        i += 2;
      } else {
        text = c.ch;
        i += 1;
      }
    }
    out.push({ text, line: c.line, column: col, ws, hidden: null });
    col += i - start;
    lastEnd = i;
  }
  return out;
}

// ------------------------------------------------------------------
// Phase 4: macro expansion
// ------------------------------------------------------------------

/**
 * Fully expand a token list (queue-splice algorithm with per-token hide
 * sets). A function-like macro is invoked only when the `(` immediately
 * follows the name (no whitespace); args are parsed with balanced parens
 * (they may span lines); each argument is pre-expanded EXCEPT when adjacent
 * to `#`/`##`; the substituted replacement list is re-scanned together with
 * the remaining input tokens — which is what makes `#define A B` +
 * `#define B(x) x` + `A(1)` expand to `1`.
 */
function expandTokens(list: PToken[], baseHidden: Set<string> | null, st: State): PToken[] {
  const queue: PToken[] = list.map((t) => ({ ...t, hidden: t.hidden ?? baseHidden ?? null }));
  const out: PToken[] = [];
  let i = 0;
  while (i < queue.length) {
    const t = queue[i];
    const m = isIdent(t.text) && !hasHidden(t, t.text) ? st.macros.get(t.text) : undefined;
    if (!m) {
      out.push(t);
      i++;
      continue;
    }
    if (m.params === null) {
      // Object-like macro.
      if (m.kind !== 'normal') {
        // Predefined dynamic macro: __LINE__ / __FILE__ / __VERSION__ / GL_ES.
        const text =
          m.kind === 'line' ? String(remap(st, t.line)) :
          m.kind === 'file' ? '0' :
          m.kind === 'version' ? String(st.version) :
          '1';
        queue.splice(i, 1, { text, line: t.line, column: t.column, ws: t.ws, hidden: t.hidden });
        continue;
      }
      const hidden = addHidden(t.hidden, t.text);
      const body = pasteTokens(markPastes(retag(m.body, t))).map((b) => ({ ...b, hidden }));
      queue.splice(i, 1, ...body);
      continue;
    }
    // Function-like macro: requires `(` immediately following (no whitespace).
    const next = queue[i + 1];
    if (next && next.text === '(' && !next.ws) {
      let depth = 1;
      let k = i + 2;
      const args: PToken[][] = [];
      let cur: PToken[] = [];
      let end = -1;
      let sawComma = false; // `F()` is zero args; `G(,)` is two empty args
      while (k < queue.length) {
        const u = queue[k];
        if (u.text === '\n') {
          // Newlines inside an argument list are whitespace (C phase 3: the
          // invocation continues across lines until the matching `)`).
          k++;
          continue;
        }
        if (u.text === '(') {
          depth++;
          cur.push(u);
          k++;
          continue;
        }
        if (u.text === ')') {
          depth--;
          if (depth === 0) {
            // `()` is ZERO arguments for a 0-parameter macro (`F()` → 42) but
            // ONE empty argument otherwise (`STR()` → `""`, per cpp/C11).
            if (sawComma || cur.length > 0 || m.params.length > 0) args.push(cur);
            end = k;
            break;
          }
          cur.push(u);
          k++;
          continue;
        }
        if (depth === 1 && u.text === ',') {
          args.push(cur);
          cur = [];
          sawComma = true;
          k++;
          continue;
        }
        cur.push(u);
        k++;
      }
      if (end < 0) {
        st.errors.push({ line: remap(st, t.line), message: `unterminated invocation of macro '${t.text}'` });
        out.push(t);
        i++;
        continue;
      }
      if (args.length !== m.params.length) {
        st.errors.push({
          line: remap(st, t.line),
          message: `macro '${t.text}' requires ${m.params.length} argument(s), but ${args.length} given`,
        });
        out.push(t);
        i++;
        continue;
      }
      const hidden = addHidden(t.hidden, t.text);
      // C99 6.10.3.1: argument pre-expansion happens with the CURRENT hide set
      // (the one the arg tokens carry at the invocation site) — the macro being
      // expanded is NOT hidden here; it is hidden only during the re-scan of
      // its own replacement text below.
      const expandedArgs = args.map((arg, ai) => (m.rawArgs[ai] ? arg : expandTokens(arg, null, st)));
      const body = substitute(m, expandedArgs, hidden, t);
      queue.splice(i, end - i + 1, ...body);
      continue;
    }
    out.push(t);
    i++;
  }
  return out;
}

/**
 * Substitute arguments into a function-like macro body: replace parameters
 * (expanded or raw per adjacency), handle `#` stringize and `##` paste, then
 * re-tag body tokens with the invocation position and hide set.
 */
function substitute(m: Macro, args: PToken[][], hidden: Set<string> | null, inv: PToken): PToken[] {
  const body = m.body;
  const out: PToken[] = [];
  for (let i = 0; i < body.length; i++) {
    const t = body[i];
    if (t.text === '#' && i + 1 < body.length) {
      const idx = m.paramIndex.get(body[i + 1].text);
      if (idx !== undefined) {
        out.push(stringize(args[idx], inv));
        i++;
        continue;
      }
      out.push({ ...t, line: inv.line, column: inv.column, hidden });
      continue;
    }
    if (t.text === '##') {
      out.push({ ...t, line: inv.line, column: inv.column, paste: true, hidden });
      continue;
    }
    const idx = m.paramIndex.get(t.text);
    if (idx !== undefined) {
      out.push(...args[idx]);
      continue;
    }
    out.push({ ...t, line: inv.line, column: inv.column, hidden });
  }
  return pasteTokens(out);
}

// ------------------------------------------------------------------
// #if expression evaluation
// ------------------------------------------------------------------

/** Parse an integer literal: hex, octal (permissive), decimal; u/f suffix stripped. */
function parseIntLiteral(text: string): number {
  const m = /^(0[xX][0-9a-fA-F]+|[0-9]+)([uUfF]*)$/.exec(text);
  if (!m) return 0;
  const body = m[1];
  if (body.length > 1 && body[0] === '0') {
    if (body[1] === 'x' || body[1] === 'X') {
      const v = parseInt(body.slice(2), 16);
      return Number.isNaN(v) ? 0 : v;
    }
    if (/^0[0-7]+$/.test(body)) return parseInt(body, 8);
  }
  const v = parseInt(body, 10);
  return Number.isNaN(v) ? 0 : v;
}

/** Replace `defined NAME` / `defined(NAME)` with 1/0 BEFORE macro expansion. */
function handleDefined(tokens: PToken[], st: State): PToken[] {
  const out: PToken[] = [];
  for (let i = 0; i < tokens.length; i++) {
    const t = tokens[i];
    if (t.text !== 'defined') {
      out.push(t);
      continue;
    }
    const next = tokens[i + 1];
    if (next && next.text === '(') {
      const id = tokens[i + 2];
      const close = tokens[i + 3];
      if (id && isIdent(id.text) && close && close.text === ')') {
        out.push({ text: st.macros.has(id.text) ? '1' : '0', line: t.line, column: t.column, ws: false, hidden: null });
        i += 3;
        continue;
      }
    } else if (next && isIdent(next.text)) {
      out.push({ text: st.macros.has(next.text) ? '1' : '0', line: t.line, column: t.column, ws: false, hidden: null });
      i += 1;
      continue;
    }
    // Malformed `defined` — left in place; the post-expansion check errors.
    out.push(t);
  }
  return out;
}

const BINOP: Record<string, { prec: number; fn: (a: number, b: number) => number }> = {
  '||': { prec: 1, fn: (a, b) => (a !== 0 || b !== 0 ? 1 : 0) },
  '&&': { prec: 2, fn: (a, b) => (a !== 0 && b !== 0 ? 1 : 0) },
  '|': { prec: 3, fn: (a, b) => (a | b) >>> 0 },
  '^': { prec: 4, fn: (a, b) => (a ^ b) >>> 0 },
  '&': { prec: 5, fn: (a, b) => (a & b) >>> 0 },
  '==': { prec: 6, fn: (a, b) => (a === b ? 1 : 0) },
  '!=': { prec: 6, fn: (a, b) => (a !== b ? 1 : 0) },
  '<': { prec: 7, fn: (a, b) => (a < b ? 1 : 0) },
  '>': { prec: 7, fn: (a, b) => (a > b ? 1 : 0) },
  '<=': { prec: 7, fn: (a, b) => (a <= b ? 1 : 0) },
  '>=': { prec: 7, fn: (a, b) => (a >= b ? 1 : 0) },
  '<<': { prec: 8, fn: (a, b) => a << b },
  '>>': { prec: 8, fn: (a, b) => a >> b },
  '+': { prec: 9, fn: (a, b) => a + b },
  '-': { prec: 9, fn: (a, b) => a - b },
  '*': { prec: 10, fn: (a, b) => a * b },
  '/': { prec: 10, fn: (a, b) => (b === 0 ? 0 : Math.trunc(a / b)) },
  '%': { prec: 10, fn: (a, b) => (b === 0 ? 0 : a % b) },
};

/** Recursive-descent (precedence climbing) parser for #if/#elif expressions. */
class ExprParser {
  private i = 0;
  private failed = false;
  /** When set, parse errors are suppressed (short-circuited && / || rhs). */
  private quiet = false;

  constructor(private readonly tokens: PToken[], private readonly st: State, private readonly line: number) {}

  parse(): number {
    const v = this.parseExpr(1);
    if (!this.failed && this.i < this.tokens.length) this.err();
    return this.failed ? 0 : v;
  }

  private err(): void {
    if (this.failed || this.quiet) return;
    this.failed = true;
    this.st.errors.push({ line: remap(this.st, this.line), message: 'invalid expression in #if' });
  }

  private peek(text: string): boolean {
    const t = this.tokens[this.i];
    return t !== undefined && t.text === text;
  }

  private parseExpr(minPrec: number): number {
    let v = this.parseUnary();
    for (;;) {
      const t = this.tokens[this.i];
      if (!t) break;
      const op = BINOP[t.text];
      if (!op || op.prec < minPrec) break;
      this.i++;
      if (op.prec === 1 || op.prec === 2) {
        // Short-circuit `||` (prec 1) and `&&` (prec 2): the right side is not
        // evaluated. It is still consumed so the parse position stays correct,
        // but errors inside it (e.g. undefined identifiers, 1/0) are ignored.
        if (op.prec === 1 ? v !== 0 : v === 0) {
          const saved = this.quiet;
          this.quiet = true;
          this.parseExpr(op.prec + 1);
          this.quiet = saved;
          v = op.prec === 1 ? 1 : 0;
        } else {
          v = op.fn(v, this.parseExpr(op.prec + 1));
        }
        continue;
      }
      v = op.fn(v, this.parseExpr(op.prec + 1));
    }
    return v;
  }

  private parseUnary(): number {
    if (this.peek('!')) {
      this.i++;
      return this.parseUnary() === 0 ? 1 : 0;
    }
    if (this.peek('~')) {
      this.i++;
      return ~this.parseUnary();
    }
    if (this.peek('+')) {
      this.i++;
      return this.parseUnary();
    }
    if (this.peek('-')) {
      this.i++;
      return -this.parseUnary();
    }
    return this.parsePrimary();
  }

  private parsePrimary(): number {
    const t = this.tokens[this.i];
    if (t === undefined) {
      this.err();
      return 0;
    }
    if (t.text === '(') {
      this.i++;
      const v = this.parseExpr(1);
      if (!this.peek(')')) {
        this.err();
        return 0;
      }
      this.i++;
      return v;
    }
    if (isDigit(t.text[0]) || (t.text[0] === '.' && t.text.length > 1)) {
      this.i++;
      return parseIntLiteral(t.text);
    }
    if (isIdent(t.text)) {
      this.i++;
      // GLSL ES §3.4: any identifier remaining after macro expansion that is
      // not a defined macro is UNDEFINED, and an undefined identifier in an
      // #if expression is an ERROR (unlike C, which substitutes 0). CTS:
      // conformance/glsl/misc/shader-with-undefined-preprocessor-symbol.frag.html.
      this.err();
      return 0;
    }
    this.err();
    return 0;
  }
}

/** Evaluate the #if/#elif condition tokens. */
function evalCondition(tokens: PToken[], line: number, st: State): number {
  if (tokens.length === 0) {
    st.errors.push({ line: remap(st, line), message: 'invalid expression in #if' });
    return 0;
  }
  const handled = handleDefined(tokens, st);
  const expanded = expandTokens(handled, null, st);
  for (const t of expanded) {
    if (t.text === 'defined') {
      // WebGL requirement: `defined` generated by macro replacement is an error.
      st.errors.push({ line: remap(st, line), message: "'defined' generated by macro expansion in #if" });
      return 0;
    }
  }
  return new ExprParser(expanded, st, line).parse();
}

// ------------------------------------------------------------------
// Directives
// ------------------------------------------------------------------

function simpleMacro(name: string, value: string): Macro {
  return {
    name,
    params: null,
    body: [{ text: value, line: 0, column: 0, ws: false, hidden: null }],
    paramIndex: new Map(),
    rawArgs: [],
    kind: 'normal',
  };
}

function sameMacro(m: Macro, params: string[] | null, body: PToken[]): boolean {
  if ((m.params === null) !== (params === null)) return false;
  if (m.params !== null && params !== null) {
    if (m.params.length !== params.length) return false;
    for (let i = 0; i < params.length; i++) {
      if (m.params[i] !== params[i]) return false;
    }
  }
  if (m.body.length !== body.length) return false;
  for (let i = 0; i < body.length; i++) {
    if (m.body[i].text !== body[i].text) return false;
  }
  return true;
}

function handleDefine(args: PToken[], line: number, st: State): void {
  if (args.length === 0 || !isIdent(args[0].text)) {
    st.errors.push({ line: remap(st, line), message: 'invalid #define directive' });
    return;
  }
  const name = args[0].text;
  if (name === 'defined') {
    st.errors.push({ line: remap(st, line), message: "'defined' cannot be used as a macro name" });
    return;
  }
  let params: string[] | null = null;
  let bodyStart = 1;
  const next = args[1];
  if (next && next.text === '(' && !next.ws) {
    // Function-like: parameters must be identifiers separated by commas.
    params = [];
    let k = 2;
    if (args[k] && args[k].text === ')') {
      k++;
    } else {
      for (;;) {
        const p = args[k];
        if (!p || !isIdent(p.text)) {
          st.errors.push({ line: remap(st, line), message: 'invalid macro parameter list' });
          return;
        }
        if (params.indexOf(p.text) >= 0) {
          st.errors.push({ line: remap(st, line), message: `duplicate macro parameter '${p.text}'` });
          return;
        }
        params.push(p.text);
        k++;
        if (args[k] && args[k].text === ',') {
          k++;
          continue;
        }
        if (args[k] && args[k].text === ')') {
          k++;
          break;
        }
        st.errors.push({ line: remap(st, line), message: 'unterminated macro parameter list' });
        return;
      }
    }
    bodyStart = k;
  }
  const body = args.slice(bodyStart);
  const existing = st.macros.get(name);
  if (existing) {
    if (sameMacro(existing, params, body)) return; // identical redefinition: legal
    st.errors.push({ line: remap(st, line), message: `redefinition of macro '${name}'` });
  }
  const paramIndex = new Map<string, number>();
  const rawArgs: boolean[] = [];
  if (params) {
    params.forEach((p, i) => paramIndex.set(p, i));
    for (let i = 0; i < params.length; i++) {
      let raw = false;
      for (let j = 0; j < body.length; j++) {
        if (body[j].text !== params[i]) continue;
        if (j > 0 && (body[j - 1].text === '#' || body[j - 1].text === '##')) raw = true;
        if (j + 1 < body.length && body[j + 1].text === '##') raw = true;
      }
      rawArgs.push(raw);
    }
  }
  st.macros.set(name, { name, params, body, paramIndex, rawArgs, kind: 'normal' });
}

function handleUndef(args: PToken[], line: number, st: State): void {
  if (args.length === 0 || !isIdent(args[0].text)) {
    st.errors.push({ line: remap(st, line), message: 'invalid #undef directive' });
    return;
  }
  if (args[0].text === 'defined') {
    st.errors.push({ line: remap(st, line), message: "'defined' cannot be used as a macro name" });
    return;
  }
  st.macros.delete(args[0].text);
}

function handleVersion(args: PToken[], line: number, st: State): void {
  if (st.sawContent) {
    st.errors.push({ line: remap(st, line), message: 'invalid #version directive: must appear before any other content' });
    return;
  }
  if (st.versionSeen) {
    // At most one #version directive may appear in a shader. CTS:
    // conformance/ogles/GL/build/build_025_to_032.html (DuplicateVersion1_V100).
    st.errors.push({ line: remap(st, line), message: 'duplicate #version directive' });
    return;
  }
  let v: 100 | 300 | null = null;
  if (args.length === 1 && args[0].text === '100') {
    v = 100;
  } else if (args.length === 2 && args[0].text === '300' && args[1].text === 'es') {
    v = 300;
  }
  if (v === null) {
    st.errors.push({ line: remap(st, line), message: 'invalid #version directive' });
    return;
  }
  if (v === 300 && st.opts.version === 100) {
    st.errors.push({ line: remap(st, line), message: 'invalid #version directive: 300 es not supported in a WebGL 1 context' });
    return;
  }
  st.version = v;
  st.versionSeen = true;
}

function handleExtension(args: PToken[], line: number, st: State): void {
  if (args.length !== 3 || args[1].text !== ':') {
    st.errors.push({ line: remap(st, line), message: 'invalid #extension directive' });
    return;
  }
  const name = args[0].text;
  const beh = args[2].text;
  if (!isIdent(name) || (beh !== 'require' && beh !== 'enable' && beh !== 'warn' && beh !== 'disable')) {
    st.errors.push({ line: remap(st, line), message: 'invalid #extension directive' });
    return;
  }
  const behavior = beh;
  st.extensionDirectives.push({ name, behavior, line: remap(st, line) });
  if (name === 'all') {
    // `all` may only be used with warn/disable (GLSL ES §3.4).
    if (behavior === 'require' || behavior === 'enable') {
      st.errors.push({ line: remap(st, line), message: "cannot use 'require' or 'enable' with 'all'" });
      return;
    }
    if (behavior === 'disable') {
      st.allState = 'disable';
      for (const n of Array.from(st.extState.keys())) {
        st.extState.delete(n);
        st.macros.delete(n);
      }
    } else {
      st.allState = 'warn';
    }
    return;
  }
  if (behavior === 'require') {
    // Only `require` of an unsupported extension is an error (GLSL ES §3.4).
    if (!st.opts.extensions || !st.opts.extensions.has(name)) {
      st.errors.push({ line: remap(st, line), message: `extension '${name}' is not supported` });
    } else {
      st.macros.set(name, simpleMacro(name, '1'));
      st.extState.set(name, behavior);
    }
  } else if (behavior === 'enable') {
    // `enable` of an unsupported extension is a warning per GLSL ES §3.4 (the
    // preprocessor has no warning channel, so accept silently) and the
    // extension is NOT enabled: no macro, no enabled-extensions entry.
    if (st.opts.extensions && st.opts.extensions.has(name)) {
      st.macros.set(name, simpleMacro(name, '1'));
      st.extState.set(name, behavior);
    }
  } else if (behavior === 'warn') {
    st.extState.set(name, 'warn');
  } else {
    st.extState.set(name, 'disable');
    st.macros.delete(name);
  }
}

function handleLine(args: PToken[], line: number, st: State): void {
  if (args.length === 0 || !/^[0-9]+$/.test(args[0].text)) {
    st.errors.push({ line: remap(st, line), message: 'invalid #line directive' });
    return;
  }
  // GLSL ES 1.00 has no source-string form: `#line` takes exactly one
  // argument. GLSL ES 3.00 adds `#line line source-string-number` (both
  // integer literals). CTS: conformance/glsl/bugs/character-set.html
  // (`#line 42 "foo.glsl"` must fail to compile).
  if (st.version === 100) {
    if (args.length !== 1) {
      st.errors.push({ line: remap(st, line), message: 'invalid #line directive: ESSL 1.00 allows only a line number' });
      return;
    }
  } else if (args.length > 2 || (args.length === 2 && !/^[0-9]+$/.test(args[1].text))) {
    st.errors.push({ line: remap(st, line), message: 'invalid #line directive' });
    return;
  }
  // The line FOLLOWING the directive becomes the given number.
  st.lineOffset = parseInt(args[0].text, 10) - (line + 1);
}

function handleError(args: PToken[], line: number, st: State): void {
  const msg = args.map((t) => t.text).join(' ');
  st.errors.push({ line: remap(st, line), message: msg.length > 0 ? msg : '#error' });
}

/** Dispatch one directive line (name token + argument tokens up to the newline). */
function dispatchDirective(dTokens: PToken[], line: number, st: State): void {
  const nameTok = dTokens[0];
  const args = dTokens.slice(1);
  const name = nameTok && isIdent(nameTok.text) ? nameTok.text : null;
  // Conditional directives are ALWAYS processed (they maintain the conditional
  // stack, including inside skipped branches). Every OTHER directive line in an
  // inactive group is ignored ENTIRELY — including malformed directive names
  // like `#$`, `#"` (GLSL ES §3.4: skipped groups are consumed, not parsed).
  // CTS: conformance/glsl/bugs/character-set.html ('in ifdef-out #preproc').
  if (name !== 'if' && name !== 'ifdef' && name !== 'ifndef' && name !== 'elif' && name !== 'else' && name !== 'endif') {
    if (!condActive(st)) return;
  }
  if (name === null) {
    st.errors.push({ line: remap(st, line), message: 'invalid directive' });
    return;
  }
  if (name !== 'version') st.sawContent = true;
  switch (name) {
    case 'if':
    case 'ifdef':
    case 'ifndef': {
      const parentActive = condActive(st);
      let taken = false;
      if (parentActive) {
        if (name === 'if') {
          taken = evalCondition(args, line, st) !== 0;
        } else {
          const nm = args[0];
          if (!nm || !isIdent(nm.text)) {
            st.errors.push({ line: remap(st, line), message: `invalid #${name} directive` });
          } else {
            const defined = st.macros.has(nm.text);
            taken = name === 'ifdef' ? defined : !defined;
          }
        }
      }
      st.condStack.push({ parentActive, taken, active: parentActive && taken, elseSeen: false, line: remap(st, line) });
      return;
    }
    case 'elif': {
      const top = st.condStack[st.condStack.length - 1];
      if (!top) {
        st.errors.push({ line: remap(st, line), message: '#elif without #if' });
        return;
      }
      if (top.elseSeen) {
        st.errors.push({ line: remap(st, line), message: '#elif after #else' });
        return;
      }
      if (top.parentActive && !top.taken) {
        if (evalCondition(args, line, st) !== 0) {
          top.taken = true;
          top.active = true;
        }
      }
      return;
    }
    case 'else': {
      const top = st.condStack[st.condStack.length - 1];
      if (!top) {
        st.errors.push({ line: remap(st, line), message: '#else without #if' });
        return;
      }
      if (top.taken) {
        top.active = false;
      } else {
        top.taken = true;
        top.active = top.parentActive;
      }
      top.elseSeen = true;
      return;
    }
    case 'endif': {
      if (st.condStack.length === 0) {
        st.errors.push({ line: remap(st, line), message: '#endif without #if' });
        return;
      }
      st.condStack.pop();
      return;
    }
    default:
      switch (name) {
        case 'define':
          handleDefine(args, line, st);
          return;
        case 'undef':
          handleUndef(args, line, st);
          return;
        case 'error':
          handleError(args, line, st);
          return;
        case 'pragma':
          return;
        case 'version':
          handleVersion(args, line, st);
          return;
        case 'extension':
          handleExtension(args, line, st);
          return;
        case 'line':
          handleLine(args, line, st);
          return;
        default:
          st.errors.push({ line: remap(st, line), message: `invalid directive '#${name}'` });
      }
  }
}

// ------------------------------------------------------------------
// Entry point
// ------------------------------------------------------------------

function initMacros(macros: Map<string, Macro>): void {
  macros.set('__LINE__', { name: '__LINE__', params: null, body: [], paramIndex: new Map(), rawArgs: [], kind: 'line' });
  macros.set('__FILE__', { name: '__FILE__', params: null, body: [], paramIndex: new Map(), rawArgs: [], kind: 'file' });
  macros.set('__VERSION__', { name: '__VERSION__', params: null, body: [], paramIndex: new Map(), rawArgs: [], kind: 'version' });
  macros.set('GL_ES', { name: 'GL_ES', params: null, body: [], paramIndex: new Map(), rawArgs: [], kind: 'gl_es' });
}

/** Tokenize a #define replacement value (used for injected `defines`). */
function charsOf(value: string): Char[] {
  const out: Char[] = [];
  let line = 1;
  for (const ch of value) {
    out.push({ ch, line });
    if (ch === '\n') line++;
  }
  return out;
}

/**
 * Run the preprocessor. Returns the expanded token stream plus the declared
 * version, enabled extensions and every #extension directive, or the list of
 * compile errors (1-based lines, after #line remapping).
 */
export function preprocess(source: string, opts: PreprocessOptions): PreprocessResult {
  const errors: CompileError[] = [];
  const st: State = {
    macros: new Map(),
    version: 100,
    lineOffset: 0,
    errors,
    extState: new Map(),
    allState: null,
    extensionDirectives: [],
    condStack: [],
    sawContent: false,
    versionSeen: false,
    opts,
  };
  initMacros(st.macros);
  if (opts.defines) {
    for (const [name, value] of Object.entries(opts.defines)) {
      if (name === 'defined') {
        errors.push({ line: 1, message: "'defined' cannot be used as a macro name" });
        continue;
      }
      const body = tokenize(charsOf(value)).filter((t) => t.text !== '\n');
      st.macros.set(name, { name, params: null, body, paramIndex: new Map(), rawArgs: [], kind: 'normal' });
    }
  }

  const tokens = tokenize(stripComments(splice(source), errors));
  const out: RawToken[] = [];
  let i = 0;
  while (i < tokens.length) {
    const t = tokens[i];
    if (t.text === '\n') {
      i++;
      continue;
    }
    const atLineStart = i === 0 || tokens[i - 1].text === '\n';
    if (t.text === '#' && atLineStart) {
      // Directive: consume the `#` plus everything up to (not incl.) the newline.
      let j = i + 1;
      while (j < tokens.length && tokens[j].text !== '\n') j++;
      const dTokens = tokens.slice(i + 1, j);
      const dline = t.line;
      i = j < tokens.length ? j + 1 : j;
      dispatchDirective(dTokens, dline, st);
      continue;
    }
    // Regular token (a `#` elsewhere is an ordinary token; the lexer validates it).
    st.sawContent = true;
    if (condActive(st)) {
      // Collect the run across newlines (function-like invocations may span
      // lines; `\n` tokens are whitespace to expansion and filtered below).
      const run: PToken[] = [];
      while (i < tokens.length) {
        const u = tokens[i];
        const uDir = u.text === '#' && (i === 0 || tokens[i - 1].text === '\n');
        if (uDir) break;
        run.push(u);
        i++;
      }
      const expanded = expandTokens(run, null, st);
      for (const e of expanded) {
        if (e.text === '\n') continue;
        out.push({ text: e.text, line: remap(st, e.line), column: e.column });
      }
    } else {
      // Skipped branch: consume without expansion, produce no tokens.
      while (i < tokens.length) {
        const u = tokens[i];
        if (u.text === '\n') break;
        const uDir = u.text === '#' && (i === 0 || tokens[i - 1].text === '\n');
        if (uDir) break;
        i++;
      }
    }
  }

  for (const f of st.condStack) {
    errors.push({ line: f.line, message: 'unterminated #if (missing #endif)' });
  }
  if (errors.length > 0) return { ok: false, errors };

  const extensions: string[] = [];
  for (const [name, beh] of st.extState) {
    if (beh === 'enable' || beh === 'require') extensions.push(name);
  }
  return { ok: true, tokens: out, version: st.version, extensions, extensionDirectives: st.extensionDirectives };
}
